### ISSUE TITLE
Bounties failure

### ISSUE THREAD

**Issue by osmnbtrclk** [zebscripts/AFK-Daily#10]
I'am getting **VerifyRGB: Failure! Expected ac5714, but got 455052 instead.** when script try to get bounties, I suppose doing this because i am already loaded every bounty with vip auto-fill.

**Comment by Zebiano** [comment]
Oh, interesting. I didn't know there was a VIP Level that would load bounties for you. You're getting the error because the script tries to load them without checking first if it can even load them. Thanks for mentioning that!

I know how to fix the problem, just I won't be able to do it in the near future. For now I recommend the following as a fix:

**Go to the very bottom of the `afk-daily.sh` file, and comment out the function that runs the bounties:**
```
# DARK FOREST TAB
switchTab "Dark Forest"
#soloBounties <- Put a hashtag at the beginning of this line
#teamBounties <- Put a hashtag at the beginning of this line (if team bounties are also affected)
arenaOfHeroes
legendsTournament
kingsTower
```
That should do the trick since the game already loads bounties for you. Hope I could help.

As a small info: Currently, I wouldn't be surprised if more things are broken on the script, as a lot os stuff has been added/changed since I last updated it. In case you start getting more errors, please wait a bit still until I managed to fix them, or you can try and check one of the updated forks of this project. [This](https://github.com/Fortigate/AFK-Daily/blob/master/deploy.sh) seems to be most updated version.
I'll update the README with a small notice regarding the plans I have with this project soon.

**Comment by Zebiano** [comment]
Also, may I ask what VIP level you're at @osmnbtrclk ?
