### ISSUE TITLE
Daily Arena fights

### ISSUE THREAD

**Issue by AllesFlauschig** [zebscripts/AFK-Daily#12]
Hello,

when i try to run the script, it works at first and after it comes to the arena fights, it just says: VerifyRGB: Failure! Expected 3c2814, but got fff0df instead.

Maybe you can help me with that.

**Comment by Zebiano** [comment]
Hey there!

The reason to that is because I haven't been updating the pixel RGB values lately. Usually every time Lilith updates it's app, the script breaks because the RGB values are wrong.

I've written a small notice on the README file. For now, I just ask for a bit of patience until I get this resolved. At least 2 weeks most likely. 

If you'd like to fix it yourself, I can try and make a quick explanation on how to. Just let me know if that interests you.

**Comment by Zebiano** [comment]
Yes it is. Check [this](https://github.com/Fortigate/AFK-Daily) fork out, it does just that.
