### ISSUE TITLE
[BUG] Exec breaks when using multiple arguments

### ISSUE THREAD

**Issue by kevingrillet** [zebscripts/AFK-Daily#155]
When I have an update, the script break because I'm using multiple arguments 😢 

The line at fault is the new `exec` one:
https://github.com/zebscripts/AFK-Daily/blob/6a154dd02ab8e58ed00fed89bd52858d31c04f64/deploy.sh#L380

It's converting the arguments in a single one and `getopts` can't do anything with it, so it's returning `Invalid option` or `illegal option`

Here is an example of the solution: <https://github.com/kevingrillet/ShellUtils/blob/main/experiments/exp_exec.sh>

Just remove the quotes, and it should work 😄

**Comment by Zebiano** [comment]
Thanks for this issue! After playing around a bit because I was not happy with the solution of ignoring this Shellcheck error, I realised that I did not find a solution to my problem. [Here's some interesting reading material.](https://github.com/koalaman/shellcheck/wiki/SC2086#exceptions)

Either way, I'll use a [directive](https://github.com/koalaman/shellcheck/wiki/Ignore#ignoring-one-specific-instance-in-a-file) to ignore this error.
