### ISSUE TITLE
[BUG] doChallengeBoss is broken

### ISSUE THREAD

**Issue by kevingrillet** [zebscripts/AFK-Daily#173]
**Describe the bug**

Should battle, but no :/
Stuck on boss level

**Expected behavior**

Multiple battles.

**Screenshots/Logs**

![image](https://user-images.githubusercontent.com/7203617/172537678-f7385da5-73ba-49e5-837b-c5dcf5bbadfc.png)

**Desktop (please complete the following information):**

- OS: W10

**Smartphone (please complete the following information):**

- Emulator: Bluestacks
- Version 5.7...

**Additional information**

https://github.com/zebscripts/AFK-Daily/blob/599949ade4e4fe54a800aa6c9732942e0225abab/afk-daily.sh#L663
![image](https://user-images.githubusercontent.com/7203617/172537770-4a26c9b3-6cda-43ca-bd50-ac298d17c91f.png)
![image](https://user-images.githubusercontent.com/7203617/172537783-4d09c922-46d7-4fa7-907b-ac372673e260.png)

**Comment by Zebiano** [comment]
This is a weird one because it works for me and I can't really reproduce it. I have double fights, so it's not because it's multibattle or anything, at least in theory.

But I do see some inconsistencies here and there, that I'm, also unsure how to fix because I don't even know why they happen in the first place. I've edited the coords to check the big "VS" letters on the top there, maybe that'll help out a bit. I'm pretty sure no matter what, those letters will be there (which is good for consistency).

**Comment by Zebiano** [comment]
Closed for now, but feel free to re-open in case it's still happening.
